import {Literal, StringOrFalse} from "./types";
import path from "path";

const someContentTypes: Literal = {
    es: 'application/ecmascript',
    gz: 'application/gzip',
    js: 'application/javascript',
    mjs: 'application/javascript',
    json: 'application/json',
    map: 'application/json',
    json5: 'application/json5',
    mp4s: 'application/mp4',
    m4p: 'application/mp4',
    doc: 'application/msword',
    dot: 'application/msword',
    cjs: 'application/node',
    bin: 'application/octet-stream',
    pkg: 'application/octet-stream',
    exe: 'application/x-msdos-program',
    dll: 'application/x-msdownload',
    deb: 'application/x-debian-package',
    dmg: 'application/x-apple-diskimage',
    iso: 'application/x-iso9660-image',
    img: 'application/octet-stream',
    msi: 'application/x-msdownload',
    msp: 'application/octet-stream',
    msm: 'application/octet-stream',
    buffer: 'application/octet-stream',
    pdf: 'application/pdf',
    pgp: 'application/pgp-encrypted',
    asc: 'application/pgp-keys',
    sig: 'application/pgp-signature',
    prf: 'application/pics-rules',
    p10: 'application/pkcs10',
    p7m: 'application/pkcs7-mime',
    p7c: 'application/pkcs7-mime',
    p7s: 'application/pkcs7-signature',
    p8: 'application/pkcs8',
    ac: 'application/pkix-attr-cert',
    cer: 'application/pkix-cert',
    crl: 'application/pkix-crl',
    pkipath: 'application/pkix-pkipath',
    pki: 'application/pkixcmp',
    pls: 'application/pls+xml',
    ai: 'application/postscript',
    eps: 'application/postscript',
    ps: 'application/postscript',
    raml: 'application/raml+yaml',
    rdf: 'application/rdf+xml',
    owl: 'application/rdf+xml',
    rsd: 'application/rsd+xml',
    rss: 'application/rss+xml',
    rtf: 'application/rtf',
    smi: 'application/smil+xml',
    smil: 'application/smil+xml',
    kml: 'application/vnd.google-earth.kml+xml',
    kmz: 'application/vnd.google-earth.kmz',
    xul: 'application/vnd.mozilla.xul+xml',
    xls: 'application/vnd.ms-excel',
    xlm: 'application/vnd.ms-excel',
    xla: 'application/vnd.ms-excel',
    xlc: 'application/vnd.ms-excel',
    xlt: 'application/vnd.ms-excel',
    xlw: 'application/vnd.ms-excel',
    xlam: 'application/vnd.ms-excel.addin.macroenabled.12',
    xlsb: 'application/vnd.ms-excel.sheet.binary.macroenabled.12',
    xlsm: 'application/vnd.ms-excel.sheet.macroenabled.12',
    xltm: 'application/vnd.ms-excel.template.macroenabled.12',
    eot: 'application/vnd.ms-fontobject',
    msg: 'application/vnd.ms-outlook',
    ppt: 'application/vnd.ms-powerpoint',
    pps: 'application/vnd.ms-powerpoint',
    oxt: 'application/vnd.openofficeorg.extension',
    osm: 'application/vnd.openstreetmap.data+xml',
    pptx: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    sldx: 'application/vnd.openxmlformats-officedocument.presentationml.slide',
    ppsx: 'application/vnd.openxmlformats-officedocument.presentationml.slideshow',
    potx: 'application/vnd.openxmlformats-officedocument.presentationml.template',
    xlsx: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    xltx: 'application/vnd.openxmlformats-officedocument.spreadsheetml.template',
    docx: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    dotx: 'application/vnd.openxmlformats-officedocument.wordprocessingml.template',
    rar: 'application/vnd.rar',
    wasm: 'application/wasm',
    lzh: 'application/x-lzh-compressed',
    lha: 'application/x-lzh-compressed',
    wmf: 'image/wmf',
    emf: 'image/emf',
    tar: 'application/x-tar',
    hdd: 'application/x-virtualbox-hdd',
    ova: 'application/x-virtualbox-ova',
    ovf: 'application/x-virtualbox-ovf',
    vbox: 'application/x-virtualbox-vbox',
    'vbox-extpack': 'application/x-virtualbox-vbox-extpack',
    vdi: 'application/x-virtualbox-vdi',
    vhd: 'application/x-virtualbox-vhd',
    vmdk: 'application/x-virtualbox-vmdk',
    der: 'application/x-x509-ca-cert',
    crt: 'application/x-x509-ca-cert',
    pem: 'application/x-x509-ca-cert',
    xml: 'application/xml',
    xsl: 'application/xml',
    xsd: 'application/xml',
    xslt: 'application/xslt+xml',
    zip: 'application/zip',
    au: 'audio/basic',
    snd: 'audio/basic',
    mid: 'audio/midi',
    midi: 'audio/midi',
    mp3: 'audio/mpeg',
    m4a: 'audio/mp4',
    mp4a: 'audio/mp4',
    mpga: 'audio/mpeg',
    mp2: 'audio/mpeg',
    mp2a: 'audio/mpeg',
    m2a: 'audio/mpeg',
    m3a: 'audio/mpeg',
    wav: 'audio/wave',
    weba: 'audio/webm',
    aac: 'audio/x-aac',
    aif: 'audio/x-aiff',
    aiff: 'audio/x-aiff',
    aifc: 'audio/x-aiff',
    flac: 'audio/x-flac',
    mka: 'audio/x-matroska',
    m3u: 'audio/x-mpegurl',
    wax: 'audio/x-ms-wax',
    wma: 'audio/x-ms-wma',
    ram: 'audio/x-pn-realaudio',
    ra: 'audio/x-pn-realaudio',
    rmp: 'audio/x-pn-realaudio-plugin',
    xm: 'audio/xm',
    otf: 'font/otf',
    ttf: 'font/ttf',
    woff: 'font/woff',
    woff2: 'font/woff2',
    bmp: 'image/bmp',
    gif: 'image/gif',
    heic: 'image/heic',
    heics: 'image/heic-sequence',
    heif: 'image/heif',
    heifs: 'image/heif-sequence',
    jp2: 'image/jp2',
    jpg2: 'image/jp2',
    jpeg: 'image/jpeg',
    jpg: 'image/jpeg',
    jpe: 'image/jpeg',
    png: 'image/png',
    svg: 'image/svg+xml',
    svgz: 'image/svg+xml',
    tif: 'image/tiff',
    ico: 'image/vnd.microsoft.icon',
    webp: 'image/webp',
    wrl: 'model/vrml',
    vrml: 'model/vrml',
    css: 'text/css',
    csv: 'text/csv',
    html: 'text/html',
    htm: 'text/html',
    shtml: 'text/html',
    markdown: 'text/markdown',
    md: 'text/markdown',
    txt: 'text/plain',
    text: 'text/plain',
    conf: 'text/plain',
    def: 'text/plain',
    list: 'text/plain',
    log: 'text/plain',
    tsv: 'text/tab-separated-values',
    vcard: 'text/vcard',
    uu: 'text/x-uuencode',
    vcs: 'text/x-vcalendar',
    vcf: 'text/x-vcard',
    yaml: 'text/yaml',
    yml: 'text/yaml',
    '3gp': 'video/3gpp',
    '3g2': 'video/3gpp2',
    h261: 'video/h261',
    h263: 'video/h263',
    h264: 'video/h264',
    jpgv: 'video/jpeg',
    jpgm: 'video/jpm',
    mp4: 'video/mp4',
    mp4v: 'video/mp4',
    mpg4: 'video/mp4',
    mpeg: 'video/mpeg',
    mpg: 'video/mpeg',
    mpe: 'video/mpeg',
    m1v: 'video/mpeg',
    m2v: 'video/mpeg',
    ogv: 'video/ogg',
    qt: 'video/quicktime',
    mov: 'video/quicktime',
    webm: 'video/webm',
    m4v: 'video/x-m4v',
    asf: 'video/x-ms-asf',
    asx: 'video/x-ms-asf',
    vob: 'video/x-ms-vob',
    wm: 'video/x-ms-wm',
    wmv: 'video/x-ms-wmv',
    wmx: 'video/x-ms-wmx',
    wvx: 'video/x-ms-wvx',
    avi: 'video/x-msvideo',
}

/*
    Select dependency or option
*/
let mime: any
try {
    mime = await import('mime-types')
}
catch (err) {
    mime = {
        contentType: (name: string): string | false => {
            const extention: string = path.extname(name).substr(1)
            console.log('mime-option', extention)
            return someContentTypes[extention] || 'text/plain'
        }
    }
}

export default mime
